/**
 * method → RequestType 映射表（Web RpcTransport 与 VsCodeTransport 共用）。
 * key 类型收窄为 HttpRpcMethod，新增 RPC 缺项会编译报错。
 */

import type { RequestType } from "vscode-jsonrpc";
import {
  AI_CONFIG_GET,
  AI_CONFIG_SET,
  AI_KEY_DELETE,
  AI_PROMPT_BUILD,
  AI_PROMPT_BUILD_DIFF,
  AI_SQL_EDIT,
  AI_TEST_CONNECTION,
  CONNECTIONS_CONNECT,
  CONNECTIONS_DELETE,
  CONNECTIONS_GET_PARAMS,
  CONNECTIONS_LIST,
  CONNECTIONS_REORDER,
  CONNECTIONS_SAVE,
  CONNECTIONS_UPDATE_META,
  DB_CANCEL_QUERY,
  DB_CAPABILITIES,
  DB_CHECK_CONSTRAINTS,
  DB_COLUMNS,
  DB_CONNECT,
  DB_DATABASE_DUMP,
  DB_DATA_TYPES,
  DB_DISCONNECT,
  DB_EXECUTE_DDL,
  DB_EXPLAIN,
  DB_EXPLAIN_TEXT,
  DB_FOREIGN_KEYS,
  DB_FUNCTION_DDL,
  DB_IMPORT_ROWS,
  DB_INDEXES,
  DB_INSTALLED_EXTENSIONS,
  DB_PARTITION_INFO,
  DB_PRIMARY_KEYS,
  DB_QUERY,
  DB_QUERY_STREAM,
  DB_QUERY_STREAM_MORE,
  DB_SAVE_CHANGES,
  DB_SCHEMA_DUMP,
  DB_SCHEMAS,
  DB_SESSION_CONTROL,
  DB_SESSION_MONITOR,
  DB_TABLE_COMMENT,
  DB_TABLE_DDL,
  DB_TABLES,
  DB_UNIQUE_CONSTRAINTS,
  QUERY_HISTORY_ADD,
  QUERY_HISTORY_CLEAR,
  QUERY_HISTORY_DELETE,
  QUERY_HISTORY_SEARCH,
  SUBSCRIPTION_ACCOUNT,
  SUBSCRIPTION_ASSERT,
  type HttpRpcMethod,
} from "../../shared/src";

export const METHOD_TYPES: Record<HttpRpcMethod, RequestType<unknown, unknown, void>> = {
  "connections/list": CONNECTIONS_LIST,
  "connections/save": CONNECTIONS_SAVE,
  "connections/delete": CONNECTIONS_DELETE,
  "connections/update-meta": CONNECTIONS_UPDATE_META,
  "connections/reorder": CONNECTIONS_REORDER,
  "connections/get-params": CONNECTIONS_GET_PARAMS,
  "connections/connect": CONNECTIONS_CONNECT,
  "query-history/add": QUERY_HISTORY_ADD,
  "query-history/search": QUERY_HISTORY_SEARCH,
  "query-history/delete": QUERY_HISTORY_DELETE,
  "query-history/clear": QUERY_HISTORY_CLEAR,
  "subscription/assert": SUBSCRIPTION_ASSERT,
  "subscription/account": SUBSCRIPTION_ACCOUNT,
  "db/connect": DB_CONNECT,
  "db/disconnect": DB_DISCONNECT,
  "db/query": DB_QUERY,
  "db/capabilities": DB_CAPABILITIES,
  "db/query-stream": DB_QUERY_STREAM,
  "db/query-stream-more": DB_QUERY_STREAM_MORE,
  "db/save-changes": DB_SAVE_CHANGES,
  "db/cancel-query": DB_CANCEL_QUERY,
  "db/explain": DB_EXPLAIN,
  "db/explain-text": DB_EXPLAIN_TEXT,
  "db/schemas": DB_SCHEMAS,
  "db/tables": DB_TABLES,
  "db/columns": DB_COLUMNS,
  "db/indexes": DB_INDEXES,
  "db/foreign-keys": DB_FOREIGN_KEYS,
  "db/data-types": DB_DATA_TYPES,
  "db/execute-ddl": DB_EXECUTE_DDL,
  "db/table-ddl": DB_TABLE_DDL,
  "db/function-ddl": DB_FUNCTION_DDL,
  "db/schema-dump": DB_SCHEMA_DUMP,
  "db/database-dump": DB_DATABASE_DUMP,
  "db/primary-keys": DB_PRIMARY_KEYS,
  "db/unique-constraints": DB_UNIQUE_CONSTRAINTS,
  "db/import-rows": DB_IMPORT_ROWS,
  "db/table-comment": DB_TABLE_COMMENT,
  "db/check-constraints": DB_CHECK_CONSTRAINTS,
  "db/partition-info": DB_PARTITION_INFO,
  "db/session-monitor": DB_SESSION_MONITOR,
  "db/session-control": DB_SESSION_CONTROL,
  "db/installed-extensions": DB_INSTALLED_EXTENSIONS,
  "ai/config/get": AI_CONFIG_GET,
  "ai/config/set": AI_CONFIG_SET,
  "ai/key/delete": AI_KEY_DELETE,
  "ai/test-connection": AI_TEST_CONNECTION,
  "ai/sql-edit": AI_SQL_EDIT,
  "ai/prompt-build": AI_PROMPT_BUILD,
  "ai/prompt-build-diff": AI_PROMPT_BUILD_DIFF,
};
